<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Test case failed]]>
    </line>
  </reporter-output>
  <suite started-at="2024-11-06T21:51:25 IST" name="Default suite" finished-at="2024-11-06T21:52:19 IST" duration-ms="54221">
    <groups>
    </groups>
    <test started-at="2024-11-06T21:51:25 IST" name="Default test" finished-at="2024-11-06T21:52:19 IST" duration-ms="54221">
      <class name="listenersP.TestScript">
        <test-method is-config="true" signature="data()[pri:0, instance:listenersP.TestScript@4d5650ae]" started-at="2024-11-06T21:51:25 IST" name="data" finished-at="2024-11-06T21:51:25 IST" duration-ms="14" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- data -->
        <test-method is-config="true" signature="launch()[pri:0, instance:listenersP.TestScript@4d5650ae]" started-at="2024-11-06T21:51:25 IST" name="launch" finished-at="2024-11-06T21:52:07 IST" duration-ms="41625" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method is-config="true" signature="login()[pri:0, instance:listenersP.TestScript@4d5650ae]" started-at="2024-11-06T21:52:07 IST" name="login" finished-at="2024-11-06T21:52:12 IST" duration-ms="5084" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="users()[pri:0, instance:listenersP.TestScript@4d5650ae]" started-at="2024-11-06T21:52:12 IST" name="users" finished-at="2024-11-06T21:52:16 IST" duration-ms="4283" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Users page not displayed expected [https://demoapp.skillrary.com/admin/user.php] but found [https://demoapp.skillrary.com/admin/users.php]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Users page not displayed expected [https://demoapp.skillrary.com/admin/user.php] but found [https://demoapp.skillrary.com/admin/users.php]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at listenersP.TestScript.users(TestScript.java:18)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test case failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- users -->
        <test-method is-config="true" signature="logout()[pri:0, instance:listenersP.TestScript@4d5650ae]" started-at="2024-11-06T21:52:16 IST" name="logout" finished-at="2024-11-06T21:52:18 IST" duration-ms="1782" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="close()[pri:0, instance:listenersP.TestScript@4d5650ae]" started-at="2024-11-06T21:52:18 IST" name="close" finished-at="2024-11-06T21:52:19 IST" duration-ms="1345" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- listenersP.TestScript -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
